<template>
  <div id="main">
    <div class="content_item">
      <h2>&Agrave; la carte Services</h2>
      <p>
        I offer several standardized services that can fit in with your existing
        experiment/work flow.
      </p>
      <div class="content_container">
        <h3>CRISPR and TALEN Optimal Target Site Selection</h3>
        <p>
          Using multiple algorithms, I will select a target site within your
          gene of interest that is optimized both for high predicted levels of
          on-target cutting and minimal potential for off-target activity
          throughout the rest of the genome. <br /><b>$200</b>
        </p>
      </div>
      <!--close content_container-->
      <div class="content_container">
        <h3>Viral Integration Site Analysis</h3>
        <p>
          I will provide a detailed protocol for preparing an Illumina
          sequencing library from cells transduced with viruses (such as
          lentiviruses). I will analyze the raw sequencing data and provide a
          comprehensive summary of the location and clonality of integration
          sites throughout the genome. <br /><b>$750</b>
        </p>
      </div>
      <!--close content_container-->
      <div class="content_container">
        <h3>Nuclease Off-Target Assay Design</h3>
        <p>
          Using predictive algorithms, I will locate the most likely sites of
          off-target activity for a nuclease (CRISPR, TALEN, or ZFN) within the
          genome of interest. I will provide PCR primer sequences and the
          overall experimental protocol for preparing a deep-sequencing library
          (either Illumina or PacBio SMRT) to evaluate levels of off-target
          activity. I will analyze the raw data generated by the sequencing
          machines and provide quantitative measurements of off-target activity.
          <br /><b>$750</b>
        </p>
      </div>
      <!--close content_container-->

      <!--<div class="content_container">
			  <h3></h3>
			  <p>
              <br><b></b></p>
			</div><!--close content_container-->
    </div>
    <!--close content_item-->
  </div>
  <!--close main-->

  <!-- javascript at the bottom for fast page loading -->
  <!--<script type="text/javascript" src="@assets/js/jquery.min.js"></script>-->
  <!--<script type="text/javascript" src="@assets/js/image_slide.js"></script>-->
</template>
